# Generated by Django 4.2.10 on 2024-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(max_length=100)),
                ('essid', models.CharField(max_length=100)),
                ('channel', models.IntegerField()),
            ],
        ),
    ]
