# Generated by Django 5.0.6 on 2024-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('bssid', models.CharField(max_length=100)),
                ('signal_strength', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
