# Generated by Django 4.2.13 on 2024-08-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_wifinetwork_remove_result_scan_remove_scan_plugin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WiFiNetwork',
        ),
    ]
