# Generated by Django 4.2.16 on 2024-12-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_delete_wifinetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
