# Generated by Django 4.2.16 on 2024-12-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_phonedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='phonedetail',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='phonedetail',
            name='father_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phonedetail',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
